USE supermarket;

DROP TABLE IF EXISTS Goods;

-- 创建商品表;
CREATE TABLE Goods (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(20) NOT NULL ,
    price DOUBLE NOT NULL ,
    quantity INT NOT NULL ,
    PRIMARY KEY (id)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;

-- 插入记录
INSERT INTO Goods (ID, NAME, PRICE, QUANTITY) VALUES (101, '番茄', 3, 100);
INSERT INTO Goods (ID, NAME, PRICE, QUANTITY) VALUES (102, '土豆', 3, 100);
INSERT INTO Goods (ID, NAME, PRICE, QUANTITY) VALUES (103, '西瓜', 3, 100);
INSERT INTO Goods (ID, NAME, PRICE, QUANTITY) VALUES (104, '纸巾', 2, 100);
INSERT INTO Goods (ID, NAME, PRICE, QUANTITY) VALUES (105, '笔', 2, 100);
INSERT INTO Goods (ID, NAME, PRICE, QUANTITY) VALUES (106, '尺子', 1.5, 100);
INSERT INTO Goods (ID, NAME, PRICE, QUANTITY) VALUES (107, '笔记本', 3, 100);
INSERT INTO Goods (ID, NAME, PRICE, QUANTITY) VALUES (108, '老干妈', 8, 100);
INSERT INTO Goods (ID, NAME, PRICE, QUANTITY) VALUES (109, '订书机', 15, 100);
INSERT INTO Goods (ID, NAME, PRICE, QUANTITY) VALUES (110, '保温杯', 79, 100);
INSERT INTO Goods (ID, NAME, PRICE, QUANTITY) VALUES (111, '雨伞', 28, 100);
INSERT INTO Goods (ID, NAME, PRICE, QUANTITY) VALUES (112, '数据线', 9.9, 100);

